# Generated by Django 2.0.9 on 2019-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
