# Generated by Django 2.0.6 on 2018-06-27 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('primary_registration_type', models.CharField(choices=[('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15)),
                ('secondary_registration_type', models.CharField(blank=True, choices=[('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15)),
                ('tertiary_registration_type', models.CharField(blank=True, choices=[('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15)),
                ('quaternary_registration_type', models.CharField(blank=True, choices=[('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
