# Generated by Django 2.0.6 on 2018-06-28 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('courses_tutoring', models.TextField()),
                ('describe_yourself', models.TextField()),
                ('linked_in_url', models.URLField()),
                ('cv', models.FileField(blank=True, upload_to='cvs/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Custom_User')),
            ],
        ),
    ]
