# Generated by Django 2.0.6 on 2018-06-28 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0003_trainer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=60)),
                ('picture', models.ImageField(blank=True, default='images/profile_pics/default_pic.jpg', null=True, upload_to='images/profile_pics')),
                ('city', models.CharField(blank=True, max_length=15)),
                ('des', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
