# Generated by Django 2.0.6 on 2018-06-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='images/course_thumbnails/default_course.jpg', null=True, upload_to='images/course_thumbnails')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('prerequisite', models.TextField()),
                ('requirements', models.TextField()),
                ('course_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Trainer_Model')),
            ],
        ),
    ]
