# Generated by Django 2.0.6 on 2018-06-28 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_answer_options_quiz_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('course_name', models.CharField(max_length=100)),
                ('linkedin_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('about_course', models.TextField(max_length=150)),
                ('about_yourself', models.TextField(max_length=150)),
                ('upload_profile', models.FileField(blank=True, null=True, upload_to='documents/trainers/')),
            ],
        ),
    ]
