# Generated by Django 2.0.6 on 2018-06-28 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_add_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('requirement', models.TextField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='job_seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('qualification', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('career_interest', models.CharField(max_length=100)),
                ('about_yourself', models.TextField(max_length=100)),
                ('upload_resume', models.FileField(blank=True, null=True, upload_to='documents/job_seeker/')),
            ],
        ),
        migrations.CreateModel(
            name='learner_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('qualification', models.CharField(max_length=30)),
                ('course_interest', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('requirement', models.TextField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
