# Generated by Django 2.0.6 on 2018-08-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('courses_subscribed', models.ManyToManyField(blank=True, null=True, to='lms.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Custom_User')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerQnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_option', to='lms.Answer_Options')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Learner_Model')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Quiz_Question')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Learner_Model')),
            ],
        ),
    ]
