# Generated by Django 2.0.6 on 2018-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_learner_model_learnerqna_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_module',
            name='allow_preview',
            field=models.NullBooleanField(default=True),
        ),
    ]
