# Generated by Django 2.0.6 on 2018-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_course_module_allow_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_module',
            name='allow_preview',
            field=models.NullBooleanField(default=False),
        ),
    ]
