# Generated by Django 2.0.6 on 2018-08-17 03:50

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20180811_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_module',
            name='labsession',
            field=models.FileField(blank=True, null=True, upload_to=lms.models.content_labsessionfile_name),
        ),
        migrations.AddField(
            model_name='course_module',
            name='reference1',
            field=models.FileField(blank=True, null=True, upload_to=lms.models.content_reference1file_name),
        ),
        migrations.AddField(
            model_name='course_module',
            name='reference2',
            field=models.FileField(blank=True, null=True, upload_to=lms.models.content_reference2file_name),
        ),
        migrations.AddField(
            model_name='course_module',
            name='reference3',
            field=models.FileField(blank=True, null=True, upload_to=lms.models.content_reference3file_name),
        ),
    ]
