# Generated by Django 2.0.6 on 2018-08-27 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitted_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_assignment', models.FileField(blank=True, null=True, upload_to='documents/submitted_assignments/')),
            ],
        ),
    ]
