# Generated by Django 2.0.6 on 2018-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_auto_20180827_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitted_assignment',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
