# Generated by Django 2.0.6 on 2018-09-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_coursefeereceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeereceipt',
            old_name='courses',
            new_name='courses_paid_for',
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coursefeereceipt',
            name='paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursefeereceipt',
            name='refund',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursefeereceipt',
            name='refund_for',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='learner_model',
            name='credit_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
