# Generated by Django 2.0.9 on 2019-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_auto_20180903_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='primary_registration_type',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='quaternary_registration_type',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='secondary_registration_type',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='tertiary_registration_type',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Learner', 'Learner'), ('Trainer', 'Trainer'), ('Vendor', 'Vendor'), ('Client', 'Client'), ('Job Seeker', 'Job Seeker')], max_length=15),
        ),
    ]
