# Generated by Django 2.0.9 on 2019-01-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_intern_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_profile',
            name='cv',
            field=models.FileField(blank=True, upload_to='documents/intern_resume/'),
        ),
    ]
