# Generated by Django 2.0.9 on 2019-01-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_intern_profile_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern_profile',
            old_name='cv',
            new_name='resume',
        ),
    ]
