# Generated by Django 2.0.9 on 2019-01-11 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_auto_20190110_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
