# Generated by Django 2.0.9 on 2019-01-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_intern_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
    ]
