# Generated by Django 2.0.9 on 2019-02-14 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0027_auto_20190111_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobseeker_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=60)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('institute', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('des', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/intern_resume/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
