# Generated by Django 2.0.9 on 2019-02-23 10:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0028_jobseeker_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='learner_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=60)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('institute', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('des', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/learner_resume/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trainer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=60)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('des', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/trainer_resume/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='documents/jobseeker_resume/'),
        ),
    ]
